name: Workflow Dispatcher

on: 
  push:
    branches: [main]

permissions:
  contents: read
  repository-projects: write

jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Disparar workflow-receiver
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"event_type":"workflow-receiver"}'
