name: Workflow Receiver

on: 
  workflow_dispatch:
    inputs:
      message:
        description: 'Mensaje recibido'
        required: false
        default: 'Sin mensaje'

jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: Recibir mensaje
        run: |
          echo "Mensaje recibido: ${{ github.event.inputs.message }}"
      
      - name: Usar secret
        env:
          MI_SECRET: ${{ secrets.SECRET_REPO }}
        run: |
          echo "Secret recibido y enmascarado: $MI_SECRET"
          echo "Workflow disparado correctamente!"
