name: Workflow Receiver

on: 
  workflow_dispatch:

jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow disparado correctamente
        run: |
          echo "✅ Workflow Receiver activado por dispatcher!"
      
      - name: Usar secret
        env:
          MI_SECRET: ${{ secrets.SECRET_REPO }}
        run: |
          echo "Secret recibido y enmascarado: $MI_SECRET"
          echo "Comunicación entre workflows exitosa!"
